# Elementos básicos de Python e Numpy

## 1\. Pacotes, e o numpy

In [6]:
import math
import numpy as np

In [7]:
math.pi

3.141592653589793

In [8]:
math.cos(math.pi)

-1.0

In [10]:
np.pi

3.141592653589793

In [12]:
np.cos(np.pi)

-1.0

In [14]:
from math import cos, pi

In [16]:
cos(pi)

-1.0

In [20]:
!pip freeze > requirements.txt

### Soma entre duas listas usando python

In [21]:
lst_a = [1, 2, 3, 4, 5]
lst_b = [6, 7, 8, 9, 10]

lst_c = []

for i in range(len(lst_a)):
    lst_c.append(lst_a[i] * lst_b[i])

print(lst_c)

[6, 14, 24, 36, 50]


### Soma entre duas listas usando numpy

In [23]:
array_a = np.array(lst_a)
array_b = np.array(lst_b)

In [25]:
array_c = array_a * array_b
array_c

array([ 6, 14, 24, 36, 50])

## 2\. NDArrays


In [27]:
import numpy as np

In [29]:
np.array([5, 2, 3, 4, 1])

array([5, 2, 3, 4, 1])

In [30]:
np.array([5, 2, 3, 4, '1'])

array(['5', '2', '3', '4', '1'], dtype='<U21')

> numpy transforma o array todo em um array de somente um tipo

In [34]:
np.array([5, 2, 3, 4, 1.])

array([5., 2., 3., 4., 1.])

In [36]:
# arrray com o tipo especificado
np.array([5, 2, 3, 4, 1], dtype='float32')

array([5., 2., 3., 4., 1.], dtype=float32)

In [39]:
# array de zeros
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

### Gerando arrays e matrizes

In [41]:
# array de numeros pares
pares = np.arange(2, 201, 2)
pares

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [44]:
# cria matriz três por dois com numero aleatórios
np.random.rand(3, 2)

array([[0.60305999, 0.737266  ],
       [0.45694529, 0.88163039],
       [0.90681977, 0.76671333]])

### Operações entre arrays

In [61]:
array_2 = np.array([2] * 5)
array_10 = np.array([10] * 5)

In [62]:
# soma mais dois em todo o array
array_2 + 2

array([4, 4, 4, 4, 4])

In [64]:
# soma cada elemento do array
array_2 + array_10

array([12, 12, 12, 12, 12])

In [66]:
# multiplica cada elemento do array
array_2 * array_10

array([20, 20, 20, 20, 20])

In [69]:
array_10 / array_2 

array([5., 5., 5., 5., 5.])

In [71]:
array_10 ** array_2 

array([100, 100, 100, 100, 100])

In [76]:
array_5 = np.array(range(1, 6))
array_5

array([1, 2, 3, 4, 5])

In [78]:
array_5 ** array_2

array([ 1,  4,  9, 16, 25])

In [79]:
array_5 ** 2

array([ 1,  4,  9, 16, 25])

## 3\. Indexação e Matrizes


In [81]:
primos = np.array([2, 3, 5, 7, 11])

In [82]:
primos[0]

2

In [84]:
primos[-3]

5

In [90]:
lst_bool = [True, False, False, True, False]

In [91]:
# Indexação boleana só trás o elemento onde o indice da lista boleada e True
primos[lst_bool]

array([2, 7])

In [99]:
# fatiamento de array
primos[-3:-1]

array([5, 7])

### Matrizes

In [104]:
matriz = np.array([[1000, 6000], [2500, 5500], [3000, 7000]])
matriz

array([[1000, 6000],
       [2500, 5500],
       [3000, 7000]])

In [119]:
# fatiando a matriz (primeiro elementos depois coluna [2:,1])

print(matriz[2:,1]) # ultimo elemento da segunda coluna

print(matriz[0:,1]) # todos os elementos da segunda coluna

print(matriz[1:,0]) # dois elementos da primeira coluna

[7000]
[6000 5500 7000]
[2500 3000]


In [112]:
matriz[:, 1] / matriz[:,0]

array([6.        , 2.2       , 2.33333333])

## 4\. Construindo e usando funções

### Escrevendo uma função def

In [127]:
imc = lambda x, y: round(x / y ** 2, 2)

In [132]:
imc(67, 1.73)

22.39

### Métodos

In [135]:
name = 'raphael oliveira'

print(name.title())
print(name.upper())
print(name.count('a'))

Raphael Oliveira
RAPHAEL OLIVEIRA
3
